"""add boost_until

Revision ID: 15a4aa5c6f74
Revises: e81f5ba09b49
Create Date: 2026-04-01 13:55:29.881268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15a4aa5c6f74'
down_revision: Union[str, Sequence[str], None] = 'e81f5ba09b49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proxies', sa.Column('boost_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proxies', 'boost_until')
    # ### end Alembic commands ###
