"""add proxy_limit to user

Revision ID: 1aa7ecd9baba
Revises: 93df6bebef6a
Create Date: 2026-03-30 14:56:22.928394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aa7ecd9baba'
down_revision: Union[str, Sequence[str], None] = '93df6bebef6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('proxy_limit', sa.Integer(), server_default='3', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'proxy_limit')
    # ### end Alembic commands ###
