"""add is_public to proxy

Revision ID: 93df6bebef6a
Revises: c6f8e1d6716a
Create Date: 2026-03-30 14:07:23.128357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93df6bebef6a'
down_revision: Union[str, Sequence[str], None] = 'c6f8e1d6716a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proxies', sa.Column('is_public', sa.Boolean(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proxies', 'is_public')
    # ### end Alembic commands ###
