"""add ref_link to users

Revision ID: b681685117e7
Revises: 04cad4e6e0ec
Create Date: 2026-04-01 11:53:56.963993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b681685117e7'
down_revision: Union[str, Sequence[str], None] = '04cad4e6e0ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ref_link', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ref_link')
    # ### end Alembic commands ###
