"""add ref_link to users

Revision ID: bd6f5609938f
Revises: b681685117e7
Create Date: 2026-04-01 12:06:58.296243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd6f5609938f'
down_revision: Union[str, Sequence[str], None] = 'b681685117e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ref_name', sa.String(length=50), nullable=True))
    op.drop_column('users', 'ref_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ref_link', sa.VARCHAR(length=50), nullable=True))
    op.drop_column('users', 'ref_name')
    # ### end Alembic commands ###
