"""add proxy_views

Revision ID: e81f5ba09b49
Revises: bd6f5609938f
Create Date: 2026-04-01 12:35:18.826774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e81f5ba09b49'
down_revision: Union[str, Sequence[str], None] = 'bd6f5609938f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proxy_views',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('proxy_id', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proxy_views_proxy_id'), 'proxy_views', ['proxy_id'], unique=False)
    op.create_index(op.f('ix_proxy_views_user_id'), 'proxy_views', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proxy_views_user_id'), table_name='proxy_views')
    op.drop_index(op.f('ix_proxy_views_proxy_id'), table_name='proxy_views')
    op.drop_table('proxy_views')
    # ### end Alembic commands ###
